### ISSUE TITLE
Close other tabs

### ISSUE THREAD

**Issue by omarserenity** [os0x/ChromeGestures#1]
I have reported this issue before in the previous version 1.12.1_0 and it exists again in 1.13.1_0.
When I use a gesture to close other tabs (or close left or right tabs) I would not expect it to close my pinned tabs (that's why they're pinned), but your functions close them regardless of their pinned status. 
To work around this, I changed the code in 
C:\Users<<my user>>\AppData\Local\Google\Chrome\User Data\Default\Extensions\jpkfjicglakibpenojifdiepckckakgk\1.13.1_0\js\TabUtils.js (around line 111 in my installation) from this:
close_other_tabs: function (tab) {
    chrome.tabs.getAllInWindow(tab.windowId, function (tabs) {
      tabs.forEach(function (_t, i) {
        if (_t.id !== tab.id) {
                chrome.tabs.remove(_t.id);
        }
      });
    });
  },
  close_right_tabs: function (tab) {
    chrome.tabs.getAllInWindow(tab.windowId, function (tabs) {
      tabs.reverse().some(function (_t, i) {
        if (_t.id !== tab.id) {
                chrome.tabs.remove(_t.id);
        } else {
          return true;
        }
      });https://github.com/os0x/ChromeGestures/wiki
    });
  },
  close_left_tabs: function (tab) {
    chrome.tabs.getAllInWindow(tab.windowId, function (tabs) {
      tabs.some(function (_t, i) {
        if (_t.id !== tab.id) {
                chrome.tabs.remove(_t.id);
        } else {
          return true;
        }
      });
    });
  },

To this:
close_other_tabs: function (tab) {
    chrome.tabs.getAllInWindow(tab.windowId, function (tabs) {
      tabs.forEach(function (_t, i) {
        if (_t.id !== tab.id) {
            if (!_t.pinned) {
                chrome.tabs.remove(_t.id);
            }
        }
      });
    });
  },
  close_right_tabs: function (tab) {
    chrome.tabs.getAllInWindow(tab.windowId, function (tabs) {
      tabs.reverse().some(function (_t, i) {
        if (_t.id !== tab.id) {
            if (!_t.pinned) {
                chrome.tabs.remove(_t.id);
            }
        } else {
          return true;
        }
      });https://github.com/os0x/ChromeGestures/wiki
    });
  },
  close_left_tabs: function (tab) {
    chrome.tabs.getAllInWindow(tab.windowId, function (tabs) {
      tabs.some(function (_t, i) {
        if (_t.id !== tab.id) {
            if (!_t.pinned) {
                chrome.tabs.remove(_t.id);
                }
        } else {
          return true;
        }
      });
    });
  },

**Comment by shogo-hta** [comment]
thank you!

**Comment by omarserenity** [comment]
You're welcome. Thank you for taking care of it.
